### ISSUE TITLE
localhost:5000 Cannot GET /

### ISSUE THREAD

**Issue by gofisk** [hollyschinsky/ConferenceTracker#2]
Hello. I was following your tutorial for this application and once I get to the step where I should test things I load localhost:5000 in my browser and get the error: Cannot GET /

When I load localhost:5000/sessions I can see all the data displayed in JSON format.

I also cloned your repository and followed the steps below to setup the app and node server.

Do you have any thoughts on what this issue might be? Thanks!

**Comment by akj627** [comment]
Change the services.js file in www/js to have this for the SessionService factory.

```
.factory('SessionService', function ($resource) {
// Node backend - works when running on emulator, browser and with PhoneGap Dev App
return $resource('http://localhost:5000/sessions/:sessionId');
// When testing directly on device using ios run, need to use the URL to your network such as below
//return $resource('http://192.168.1.5:5000/sessions/:sessionId');
})
```

Basically, you are commenting the ip address and using localhost as written in the comment.
Hope it works

**Comment by gofisk** [comment]
My services.js file already has localhost:5000 for the address. I copied and pasted your code to make sure there weren't any other differences, but it didn't seem to help at all. Any other thoughts?

**Comment by akj627** [comment]
Please use jsfiddle or plunkr to show your project and I can help.

Also, if possible, grab any console errors and let me know....

**Comment by gofisk** [comment]
I figured it out! There was no route defined in the server.js file provided from this repository. I added the code below and voila! Thanks for your help!

app.get('/', function (req, res) {
  res.render('index', {});
});
